server:
  port: 8080
  servlet:
    context-path: /shop

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.40.128:3306/secondhandmarket?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/secondhandmarket?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
  resources:
    static-locations: classpath:/staic/,classpath:/css/,classpath:/img/,classpath:/fonts/,classpath:/font-awesome,classpath:/pages,classpath:/WEB-INF/jsp/error/,classpath:/upload/,classpath:/META-INF/,classpath:/js/,classpath:/resources/templates/error/

# 打印sql语句
logging:
  level:
    com.secondary.market.mapper: debug

mybatis:
  configuration:
  # 驼峰命名
    map-underscore-to-camel-case: true
  # 配置别名
  type-aliases-package: com.secondary.market.domain
  # 配置mapper
  mapper-locations: classpath:mapper/*.xml

# pagehelper配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  reasonable: true
  params: pageNum=start;pageSize=limit;
  support-methods-arguments: true


